on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
jobs:
  job:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/openskiron.sh
      - uses: actions4git/add-commit-push@v1
