on:
  push:
    branches:
      - main
  schedule:
    - cron: '25 */3 * * *'
jobs:
  job:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install bs4
      - run: scripts/openskiron.sh
      - run: date --iso-8601=sec -u > openskiron.ts
      - uses: actions4git/add-commit-push@v1
